plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Gwen
description: This is my Jekyll website that is running Simple.css
lang: en
locale: en_US
url: "https://"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20